# Generated by Django 3.2.4 on 2021-06-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210514_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='account_email',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='newuser',
            name='business_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='newuser',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_attendant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
