# Generated by Django 3.2.4 on 2021-06-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_newuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='is_staff',
        ),
    ]
