# Generated by Django 3.2.4 on 2021-08-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_newuser_account_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='business_name',
        ),
    ]
